config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'
  
  get 'static_pages/upload'
  get '/kalliope' => 'static_pages#admin'

  resources :paintings
  
  root 'static_pages#home'

end

app/models/painting.rb
class Painting < ActiveRecord::Base
    mount_uploader :my_file, FileUploader
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :paintings         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]


  # GET /paintings
  # GET /paintings.json
  def index
    @paintings = Painting.all
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
    @paintings = Painting.all
  end

  # GET /paintings/new
  def new
    @painting = current_user.paintings.build
  end

  # GET /paintings/1/edit
  def edit
  end

  # POST /paintings
  # POST /paintings.json
  def create
    @painting = current_user.paintings.build(painting_params)
    @painting.my_file = params[:file]
    respond_to do |format|
      if @painting.save
        format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
        format.json { render :show, status: :created, location: @painting }
      else
        format.html { render :new }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paintings/1
  # PATCH/PUT /paintings/1.json
  def update
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
        format.json { render :show, status: :ok, location: @painting }
      else
        format.html { render :edit }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting.destroy
    respond_to do |format|
      format.html { redirect_to paintings_url, notice: 'Painting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painting_params
      params.fetch(:painting, {})
      params.require(:painting).permit(:my_file, :title, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @paintings = Painting.all
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Coda' rel='stylesheet' type='text/css'>
</head>
<body>
<%= link_to "admin", kalliope_path %>
  <!--TEMPORARY COMMENTS FOR DEVISE-->
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
   <!--TEMPORARY COMMENTS FOR DEVISE-->
   
  <div class="site_container">
    <%= render 'shared/header' %>
    <%= render 'shared/top_links' %>
    <div class="main_wrapper">
      <%= yield %>
      <%= render 'shared/footer' %>
    </div>
  </div>
</body>
</html>

app/views/paintings/_form.html.erb
<%= form_for(@painting) do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>

      <ul>
      <% @painting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :Tytuł %> <br>
    <%= f.text_field :title %> <br>
  </div>
  
  <div class="field"> 
    <%= f.label :Opis %> <br>
    <%= f.text_area :description %> <br>
  </div> 
  
  <div class="field">
    <%= f.label :Plik %>  <br>
    <%= f.file_field :my_file %> <br>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paintings/edit.html.erb
<h1>Editing Painting</h1>

<%= render 'form' %>
<ul>
    <li><%= link_to 'Wyświetl obraz', @painting %></li>
    <li><%= link_to 'Powrót', paintings_path %></li>

</ul>

app/views/paintings/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Obrazki</h1>

<ul>
  <li><%= link_to 'Dodaj Obrazek', new_painting_path %></li>
  <li><%= link_to 'Powrót', kalliope_path %></li>
</ul>


<div class="paintings-index-wrapper">
  <% @paintings.each do |painting| %>
    <div class="paintings-index">
    <%= link_to image_tag("#{painting.my_file.url(:thumb)}"), painting %>
       <div class="paintings-links">
         <a href="<%= painting.my_file %>">Pobierz</a>
         <%= link_to 'Edycja', edit_painting_path(painting) %>
         <%= link_to 'Usuń', painting, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>



<!--INITIAL TABLE DISPLAY OF PAINTINGS PROVIDED BY SCAFFOLDING-->
  <!--<table>-->
  <!--  <thead>-->
  <!--    <tr>-->
  <!--      <th colspan="3"></th>-->
  <!--    </tr>-->
  <!--  </thead>-->
  
  <!--  <tbody>-->
  <!--    <% @paintings.each do |painting| %>-->
  <!--      <tr>-->
  <!--        <td><%= link_to image_tag("#{painting.my_file}"), painting %></td>-->
  <!--        <td><a href="<%= painting.my_file %>">Download</a></td>-->
  <!--        <td><%= link_to 'Show', painting %></td>-->
  <!--        <td><%= link_to 'Edit', edit_painting_path(painting) %></td>-->
  <!--        <td><%= link_to 'Destroy', painting, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
  <!--      </tr>-->
  <!--    <% end %>-->
  <!--  </tbody>-->
  <!--</table>-->
<!--INITIAL TABLE DISPLAY OF PAINTINGS PROVIDED BY SCAFFOLDING-->
  
  <br>




    

app/views/paintings/new.html.erb
<h1>New Painting</h1>

<%= render 'form' %>

<%= link_to 'Back', paintings_path %>

app/views/paintings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="paintings-show-wrapper">
  <h1><%= @painting.title %></h1>
  <p><%= @painting.description %></p>
  <!--added for reference how to combine link_to and image_tag-->
    <!--<%= image_tag("#{@painting.my_file}") %>-->
    <!--<%= link_to image_tag("#{@painting.my_file.url(:medium)}"), painting_path(@painting) %>-->
  <!--added for reference how to combine link_to and image_tag-->
   <a href="<%= @painting.my_file %>"><%= image_tag("#{@painting.my_file.url(:medium)}") %></a>
</div>
<% if user_signed_in? %>
  <div class="paintings-nav">
    <ul>
      <li><%= link_to 'Edit', edit_painting_path(@painting) %></li>
      <li><%= link_to 'Back', paintings_path %></li>          
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">Code and Design by Yendrek</div>

app/views/shared/_header.html.erb
<div class="header">
    <h1>Fotoblografix</h1>
    <p>Dominika Ciepielewska</p>
</div>

app/views/shared/_top_links.html.erb
<ul class="top-links">
  <li><%= link_to 'Portfolio', static_pages_home_path %></li>
  <li><%= link_to 'O mnie', static_pages_about_path %></li>
  <li><%= link_to 'Kontakt', static_pages_contact_path %></li>
  <% if user_signed_in? && current_user.admin == true  %>
    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    <li><%= link_to 'Admin', paintings_path %></li>
  <% end %>
</ul>

app/views/static_pages/about.html.erb
<h1>O mnie</h1>

<div class="about-whole-wrapper">
  <div class="about-avatar">
    <p><%= image_tag("avatar.png", :class => "avatar") %></p>
  </div>
  <div class="about-wrapper">
    <div class="about-description">
      <p>Studentka konserwacji i restauracji dzieł sztuki, specjalizacji malarstwa Akademii Sztuk Pięknych im. Jana Matejki w Krakowie.
      Zajmuję się również konserwacją archiwalnych materiałów fotograficznych (II letni kurs na ASP Kraków).
      Hobbystycznie uprawiam grafikę warsztatową i cyfrową oraz zajmuję się fotografiką tradycyjną w nurcie street fotography,
      a także pejzażową  i portretową - głównie osób bliskich.</p>
      
      <p>Obecny blog autorski to swego rodzaju azyl promujący zbiór szeroko pojętej twórczości wizualnej,
      do którego chciałabym teraz serdecznie zaprosić Ciebie, Drogi Widzu.</p>  
      
      <p>Miłego odbioru!</p>
    </div>
  </div>
</div>

app/views/static_pages/admin.html.erb
<h1>Admin Panel</h1>

<ul>
  <li><%= link_to 'Panel Administracyjny', paintings_path %></li>
  <% if user_signed_in? %>
    <li><%= link_to('Wyloguj', destroy_user_session_path, :method => :delete) %></li>
  <% end %>
</ul>

<!--<li><%= link_to 'Login', new_user_session_path %></li>-->
<!--<li><%= link_to 'Rejestracja', new_user_registration_path %></li>-->

app/views/static_pages/contact.html.erb
<h1>Kontakt</h1>
<h2>facebook.com/fotoblografix</h2>
<h2>dominika.ciepielewska@gmail.com</h2>

app/views/static_pages/home.html.erb
<h1>Portfolio</h1>
<div class="home-gallery">
  <% @paintings.each do |painting| %>
  <div class="home-thumbnail">
    <div class="thumbnail-wrapper">    
    <%= link_to image_tag("#{painting.my_file.url(:thumb)}"), painting %>
    </div>
    <div class="thumbnail-title">
    <%= painting.title %> 
    </div>
   </div>
  <% end %>
</div>

app/views/static_pages/upload.html.erb
<h1>Panel administracyjny</h1>
<ul>
 <li><%= link_to 'Zarządzaj obrazkami', paintings_path %></li>
</ul>